version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: evv_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: evv_golang_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_SOURCE: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
    restart: unless-stopped

volumes:
  postgres_data:
